name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go mod tidy
        run: go mod tidy

      - name: Verify
        run: go mod verify

      - name: Build
        run: go build ./cmd/uupt-open-cli

      - name: Test
        run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Go vet
        run: go vet ./...

      - name: Go fmt
        run: |
          out=$(gofmt -l .)
          if [ -n "$out" ]; then
            echo "以下文件格式不正确："
            echo "$out"
            exit 1
          fi
